Resources:
      Table:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:service.name}-dynamodb
            AttributeDefinitions:
                - AttributeName: type
                  AttributeType: S
                - AttributeName: name
                  AttributeType: S
            KeySchema:
                - AttributeName: type
                  KeyType: HASH
                - AttributeName: name
                  KeyType: RANGE
            BillingMode: PAY_PER_REQUEST


